spring:
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: mail-server
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
